# CSA of 13C from the guanidinium of GLAL2 as monomer and dimer
## Details
* monomer calculated at PBE0/pcSseg-2 LOT 
* dimer calculated at PBE0/pcSseg-1 LOT


In [25]:
# Get the NONCOVToolbox library and print header
%load_ext autoreload
%autoreload 2

import sys
import os
import pandas as pd
import matplotlib.pyplot as plt
import glob
import numpy as np
from sklearn.cluster import KMeans
import pathlib as Path
import importlib

path_noncov = os.path.abspath(os.path.join('..', '..', 'src'))

if path_noncov not in sys.path:
    sys.path.append(path_noncov)

from noncov import NONCOVToolbox, NONCOVHeader

noncov = NONCOVToolbox()

#NONCOVHeader.print_header()

# Show performance and features of various NMR functions in module
from noncov import NMRFunctions

# Disable printing
def blockPrint():
    sys.stdout = open(os.devnull, 'w')

# Restore printing
def enablePrint():
    sys.stdout = sys.__stdout__

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [26]:
MonomerCSA13C = [[120.274,          2.665,        42.176],
             [5.735,        -13.508,         2.337],
            [41.749,        1.091,       -18.002]]

DimerCSA13C = [[120.510, 4.861, 40.703], [6.972, -12.468, 1.481], [41.517, 0.547, -9.711]]


In [27]:
shielding_tensor, s_iso, diagonal_mehring, eigenvals, eigenvecs, symmetry, span, skew, diagonal_haberlen, red_anisotropy, asymmetry, anisotropy = NMRFunctions().diagonalize_tensor(DimerCSA13C)

# -------------------------------------------------- #
# TENSOR DIAGONALIZATION FUNCTION HAS BEEN REQUESTED #


Shielding Tensor is: 
[[120.51    4.861  40.703]
 [  6.972 -12.468   1.481]
 [ 41.517   0.547  -9.711]]
Proceeding to transposing...

Transposed matrix is: 
[[120.51    6.972  41.517]
 [  4.861 -12.468   0.547]
 [ 40.703   1.481  -9.711]]
Proceeding to symmetrization...

Symmetric tensor is: 
[[120.51     5.9165  41.11  ]
 [  5.9165 -12.468    1.014 ]
 [ 41.11     1.014   -9.711 ]]

Antisymmetric tensor is. 
[[ 0.     -1.0555 -0.407 ]
 [ 1.0555  0.      0.467 ]
 [ 0.407  -0.467   0.    ]]

Since antisymmetric part does not contribute to observable but only to relaxation, skipping...

Proceeding to diagonalization...

Eigenvalues are: [132.65 -21.65 -12.66], Eigenvectors are: 
[[ 0.96  0.28  0.02]
 [ 0.04 -0.07 -1.  ]
 [ 0.28 -0.96  0.08]]

Proceeding to ordering eigenvalues and eigenvectors...

Magnitude-based ordering of eigenvalues is: 
[-12.66 -21.65 132.65] 
 and of eigen

In [28]:
shielding_tensor, s_iso, diagonal_mehring, eigenvals, eigenvecs, symmetry, span, skew, diagonal_haberlen, red_anisotropy, asymmetry, anisotropy = NMRFunctions().diagonalize_tensor(MonomerCSA13C)

# -------------------------------------------------- #
# TENSOR DIAGONALIZATION FUNCTION HAS BEEN REQUESTED #


Shielding Tensor is: 
[[120.274   2.665  42.176]
 [  5.735 -13.508   2.337]
 [ 41.749   1.091 -18.002]]
Proceeding to transposing...

Transposed matrix is: 
[[120.274   5.735  41.749]
 [  2.665 -13.508   1.091]
 [ 42.176   2.337 -18.002]]
Proceeding to symmetrization...

Symmetric tensor is: 
[[120.274    4.2     41.9625]
 [  4.2    -13.508    1.714 ]
 [ 41.9625   1.714  -18.002 ]]

Antisymmetric tensor is. 
[[ 0.     -1.535   0.2135]
 [ 1.535   0.      0.623 ]
 [-0.2135 -0.623   0.    ]]

Since antisymmetric part does not contribute to observable but only to relaxation, skipping...

Proceeding to diagonalization...

Eigenvalues are: [132.15 -29.76 -13.63], Eigenvectors are: 
[[ 0.96  0.27  0.04]
 [ 0.03  0.03 -1.  ]
 [ 0.27 -0.96 -0.02]]

Proceeding to ordering eigenvalues and eigenvectors...

Magnitude-based ordering of eigenvalues is: 
[-13.63 -29.76 132.15] 
 and of eigen

In [21]:
components = [abs(eigenvals[0]-s_iso), abs(eigenvals[1]-s_iso), abs(eigenvals[2]-s_iso)]

In [22]:
components

[102.56, 59.35, 43.22]

In [23]:
asymmetry = (components[2]-components[1]) / components[0]
asymmetry

-0.1572737909516381

In [24]:
anisotropy = (3*components[0])/2
anisotropy

153.84